// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fury/incentive/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Selection is a pair of denom and multiplier name. It holds the choice of multiplier a user makes when they claim a
// denom.
type Selection struct {
	Denom          string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	MultiplierName string `protobuf:"bytes,2,opt,name=multiplier_name,json=multiplierName,proto3" json:"multiplier_name,omitempty"`
}

func (m *Selection) Reset()         { *m = Selection{} }
func (m *Selection) String() string { return proto.CompactTextString(m) }
func (*Selection) ProtoMessage()    {}
func (*Selection) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{0}
}
func (m *Selection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Selection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Selection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Selection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Selection.Merge(m, src)
}
func (m *Selection) XXX_Size() int {
	return m.Size()
}
func (m *Selection) XXX_DiscardUnknown() {
	xxx_messageInfo_Selection.DiscardUnknown(m)
}

var xxx_messageInfo_Selection proto.InternalMessageInfo

// MsgClaimUSDFMintingReward message type used to claim USDF minting rewards
type MsgClaimUSDFMintingReward struct {
	Sender         string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	MultiplierName string `protobuf:"bytes,2,opt,name=multiplier_name,json=multiplierName,proto3" json:"multiplier_name,omitempty"`
}

func (m *MsgClaimUSDFMintingReward) Reset()         { *m = MsgClaimUSDFMintingReward{} }
func (m *MsgClaimUSDFMintingReward) String() string { return proto.CompactTextString(m) }
func (*MsgClaimUSDFMintingReward) ProtoMessage()    {}
func (*MsgClaimUSDFMintingReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{1}
}
func (m *MsgClaimUSDFMintingReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimUSDFMintingReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimUSDFMintingReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimUSDFMintingReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimUSDFMintingReward.Merge(m, src)
}
func (m *MsgClaimUSDFMintingReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimUSDFMintingReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimUSDFMintingReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimUSDFMintingReward proto.InternalMessageInfo

// MsgClaimUSDFMintingRewardResponse defines the Msg/ClaimUSDFMintingReward response type.
type MsgClaimUSDFMintingRewardResponse struct {
}

func (m *MsgClaimUSDFMintingRewardResponse) Reset()         { *m = MsgClaimUSDFMintingRewardResponse{} }
func (m *MsgClaimUSDFMintingRewardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimUSDFMintingRewardResponse) ProtoMessage()    {}
func (*MsgClaimUSDFMintingRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{2}
}
func (m *MsgClaimUSDFMintingRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimUSDFMintingRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimUSDFMintingRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimUSDFMintingRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimUSDFMintingRewardResponse.Merge(m, src)
}
func (m *MsgClaimUSDFMintingRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimUSDFMintingRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimUSDFMintingRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimUSDFMintingRewardResponse proto.InternalMessageInfo

// MsgClaimJinxReward message type used to claim Jinx liquidity provider rewards
type MsgClaimJinxReward struct {
	Sender        string     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	DenomsToClaim Selections `protobuf:"bytes,2,rep,name=denoms_to_claim,json=denomsToClaim,proto3,castrepeated=Selections" json:"denoms_to_claim"`
}

func (m *MsgClaimJinxReward) Reset()         { *m = MsgClaimJinxReward{} }
func (m *MsgClaimJinxReward) String() string { return proto.CompactTextString(m) }
func (*MsgClaimJinxReward) ProtoMessage()    {}
func (*MsgClaimJinxReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{3}
}
func (m *MsgClaimJinxReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimJinxReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimJinxReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimJinxReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimJinxReward.Merge(m, src)
}
func (m *MsgClaimJinxReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimJinxReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimJinxReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimJinxReward proto.InternalMessageInfo

// MsgClaimJinxRewardResponse defines the Msg/ClaimJinxReward response type.
type MsgClaimJinxRewardResponse struct {
}

func (m *MsgClaimJinxRewardResponse) Reset()         { *m = MsgClaimJinxRewardResponse{} }
func (m *MsgClaimJinxRewardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimJinxRewardResponse) ProtoMessage()    {}
func (*MsgClaimJinxRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{4}
}
func (m *MsgClaimJinxRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimJinxRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimJinxRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimJinxRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimJinxRewardResponse.Merge(m, src)
}
func (m *MsgClaimJinxRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimJinxRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimJinxRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimJinxRewardResponse proto.InternalMessageInfo

// MsgClaimDelegatorReward message type used to claim delegator rewards
type MsgClaimDelegatorReward struct {
	Sender        string     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	DenomsToClaim Selections `protobuf:"bytes,2,rep,name=denoms_to_claim,json=denomsToClaim,proto3,castrepeated=Selections" json:"denoms_to_claim"`
}

func (m *MsgClaimDelegatorReward) Reset()         { *m = MsgClaimDelegatorReward{} }
func (m *MsgClaimDelegatorReward) String() string { return proto.CompactTextString(m) }
func (*MsgClaimDelegatorReward) ProtoMessage()    {}
func (*MsgClaimDelegatorReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{5}
}
func (m *MsgClaimDelegatorReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimDelegatorReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimDelegatorReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimDelegatorReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimDelegatorReward.Merge(m, src)
}
func (m *MsgClaimDelegatorReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimDelegatorReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimDelegatorReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimDelegatorReward proto.InternalMessageInfo

// MsgClaimDelegatorRewardResponse defines the Msg/ClaimDelegatorReward response type.
type MsgClaimDelegatorRewardResponse struct {
}

func (m *MsgClaimDelegatorRewardResponse) Reset()         { *m = MsgClaimDelegatorRewardResponse{} }
func (m *MsgClaimDelegatorRewardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimDelegatorRewardResponse) ProtoMessage()    {}
func (*MsgClaimDelegatorRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{6}
}
func (m *MsgClaimDelegatorRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimDelegatorRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimDelegatorRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimDelegatorRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimDelegatorRewardResponse.Merge(m, src)
}
func (m *MsgClaimDelegatorRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimDelegatorRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimDelegatorRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimDelegatorRewardResponse proto.InternalMessageInfo

// MsgClaimSwapReward message type used to claim delegator rewards
type MsgClaimSwapReward struct {
	Sender        string     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	DenomsToClaim Selections `protobuf:"bytes,2,rep,name=denoms_to_claim,json=denomsToClaim,proto3,castrepeated=Selections" json:"denoms_to_claim"`
}

func (m *MsgClaimSwapReward) Reset()         { *m = MsgClaimSwapReward{} }
func (m *MsgClaimSwapReward) String() string { return proto.CompactTextString(m) }
func (*MsgClaimSwapReward) ProtoMessage()    {}
func (*MsgClaimSwapReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{7}
}
func (m *MsgClaimSwapReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimSwapReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimSwapReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimSwapReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimSwapReward.Merge(m, src)
}
func (m *MsgClaimSwapReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimSwapReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimSwapReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimSwapReward proto.InternalMessageInfo

// MsgClaimSwapRewardResponse defines the Msg/ClaimSwapReward response type.
type MsgClaimSwapRewardResponse struct {
}

func (m *MsgClaimSwapRewardResponse) Reset()         { *m = MsgClaimSwapRewardResponse{} }
func (m *MsgClaimSwapRewardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimSwapRewardResponse) ProtoMessage()    {}
func (*MsgClaimSwapRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{8}
}
func (m *MsgClaimSwapRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimSwapRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimSwapRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimSwapRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimSwapRewardResponse.Merge(m, src)
}
func (m *MsgClaimSwapRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimSwapRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimSwapRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimSwapRewardResponse proto.InternalMessageInfo

// MsgClaimSavingsReward message type used to claim savings rewards
type MsgClaimSavingsReward struct {
	Sender        string     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	DenomsToClaim Selections `protobuf:"bytes,2,rep,name=denoms_to_claim,json=denomsToClaim,proto3,castrepeated=Selections" json:"denoms_to_claim"`
}

func (m *MsgClaimSavingsReward) Reset()         { *m = MsgClaimSavingsReward{} }
func (m *MsgClaimSavingsReward) String() string { return proto.CompactTextString(m) }
func (*MsgClaimSavingsReward) ProtoMessage()    {}
func (*MsgClaimSavingsReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{9}
}
func (m *MsgClaimSavingsReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimSavingsReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimSavingsReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimSavingsReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimSavingsReward.Merge(m, src)
}
func (m *MsgClaimSavingsReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimSavingsReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimSavingsReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimSavingsReward proto.InternalMessageInfo

// MsgClaimSavingsRewardResponse defines the Msg/ClaimSavingsReward response type.
type MsgClaimSavingsRewardResponse struct {
}

func (m *MsgClaimSavingsRewardResponse) Reset()         { *m = MsgClaimSavingsRewardResponse{} }
func (m *MsgClaimSavingsRewardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimSavingsRewardResponse) ProtoMessage()    {}
func (*MsgClaimSavingsRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{10}
}
func (m *MsgClaimSavingsRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimSavingsRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimSavingsRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimSavingsRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimSavingsRewardResponse.Merge(m, src)
}
func (m *MsgClaimSavingsRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimSavingsRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimSavingsRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimSavingsRewardResponse proto.InternalMessageInfo

// MsgClaimEarnReward message type used to claim earn rewards
type MsgClaimEarnReward struct {
	Sender        string     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	DenomsToClaim Selections `protobuf:"bytes,2,rep,name=denoms_to_claim,json=denomsToClaim,proto3,castrepeated=Selections" json:"denoms_to_claim"`
}

func (m *MsgClaimEarnReward) Reset()         { *m = MsgClaimEarnReward{} }
func (m *MsgClaimEarnReward) String() string { return proto.CompactTextString(m) }
func (*MsgClaimEarnReward) ProtoMessage()    {}
func (*MsgClaimEarnReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{11}
}
func (m *MsgClaimEarnReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimEarnReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimEarnReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimEarnReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimEarnReward.Merge(m, src)
}
func (m *MsgClaimEarnReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimEarnReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimEarnReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimEarnReward proto.InternalMessageInfo

// MsgClaimEarnRewardResponse defines the Msg/ClaimEarnReward response type.
type MsgClaimEarnRewardResponse struct {
}

func (m *MsgClaimEarnRewardResponse) Reset()         { *m = MsgClaimEarnRewardResponse{} }
func (m *MsgClaimEarnRewardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimEarnRewardResponse) ProtoMessage()    {}
func (*MsgClaimEarnRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e1c6edfdd8e91a, []int{12}
}
func (m *MsgClaimEarnRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimEarnRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimEarnRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimEarnRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimEarnRewardResponse.Merge(m, src)
}
func (m *MsgClaimEarnRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimEarnRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimEarnRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimEarnRewardResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Selection)(nil), "fury.incentive.v1beta1.Selection")
	proto.RegisterType((*MsgClaimUSDFMintingReward)(nil), "fury.incentive.v1beta1.MsgClaimUSDFMintingReward")
	proto.RegisterType((*MsgClaimUSDFMintingRewardResponse)(nil), "fury.incentive.v1beta1.MsgClaimUSDFMintingRewardResponse")
	proto.RegisterType((*MsgClaimJinxReward)(nil), "fury.incentive.v1beta1.MsgClaimJinxReward")
	proto.RegisterType((*MsgClaimJinxRewardResponse)(nil), "fury.incentive.v1beta1.MsgClaimJinxRewardResponse")
	proto.RegisterType((*MsgClaimDelegatorReward)(nil), "fury.incentive.v1beta1.MsgClaimDelegatorReward")
	proto.RegisterType((*MsgClaimDelegatorRewardResponse)(nil), "fury.incentive.v1beta1.MsgClaimDelegatorRewardResponse")
	proto.RegisterType((*MsgClaimSwapReward)(nil), "fury.incentive.v1beta1.MsgClaimSwapReward")
	proto.RegisterType((*MsgClaimSwapRewardResponse)(nil), "fury.incentive.v1beta1.MsgClaimSwapRewardResponse")
	proto.RegisterType((*MsgClaimSavingsReward)(nil), "fury.incentive.v1beta1.MsgClaimSavingsReward")
	proto.RegisterType((*MsgClaimSavingsRewardResponse)(nil), "fury.incentive.v1beta1.MsgClaimSavingsRewardResponse")
	proto.RegisterType((*MsgClaimEarnReward)(nil), "fury.incentive.v1beta1.MsgClaimEarnReward")
	proto.RegisterType((*MsgClaimEarnRewardResponse)(nil), "fury.incentive.v1beta1.MsgClaimEarnRewardResponse")
}

func init() { proto.RegisterFile("fury/incentive/v1beta1/tx.proto", fileDescriptor_e6e1c6edfdd8e91a) }

var fileDescriptor_e6e1c6edfdd8e91a = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x33, 0xbb, 0xec, 0xe2, 0x3e, 0xd1, 0x85, 0xa1, 0xd6, 0x1a, 0x34, 0xd9, 0xd6, 0x83,
	0x8b, 0xb0, 0x09, 0xad, 0x88, 0xe8, 0x71, 0x5d, 0x05, 0x85, 0x7a, 0x68, 0xd7, 0x8b, 0x20, 0x65,
	0xda, 0xce, 0xc6, 0x81, 0x64, 0x26, 0x66, 0xa6, 0xdd, 0xae, 0x27, 0x4f, 0xe2, 0xd1, 0x8b, 0x20,
	0x9e, 0xf6, 0xec, 0x27, 0xd9, 0xe3, 0x1e, 0x3d, 0xa9, 0xb4, 0x20, 0x7e, 0x0c, 0x69, 0xda, 0x26,
	0x61, 0x93, 0x10, 0xeb, 0xa9, 0xb7, 0xcc, 0xcc, 0xff, 0xbd, 0xf7, 0xfb, 0x3f, 0xf2, 0x66, 0xc0,
	0x3c, 0x1a, 0x04, 0x27, 0x36, 0xe3, 0x3d, 0xca, 0x15, 0x1b, 0x52, 0x7b, 0x58, 0xef, 0x52, 0x45,
	0xea, 0xb6, 0x1a, 0x59, 0x7e, 0x20, 0x94, 0xc0, 0xe5, 0xa9, 0xc0, 0x8a, 0x04, 0xd6, 0x5c, 0xa0,
	0x97, 0x1c, 0xe1, 0x88, 0x50, 0x62, 0x4f, 0xbf, 0x66, 0xea, 0xda, 0x21, 0x6c, 0xb5, 0xa9, 0x4b,
	0x7b, 0x8a, 0x09, 0x8e, 0x4b, 0xb0, 0xd1, 0xa7, 0x5c, 0x78, 0x15, 0xb4, 0x83, 0x76, 0xb7, 0x5a,
	0xb3, 0x05, 0xbe, 0x03, 0xdb, 0xde, 0xc0, 0x55, 0xcc, 0x77, 0x19, 0x0d, 0x3a, 0x9c, 0x78, 0xb4,
	0xb2, 0x16, 0x9e, 0x5f, 0x8d, 0xb7, 0x5f, 0x10, 0x8f, 0x3e, 0xba, 0xf4, 0xf1, 0xd4, 0xd4, 0xfe,
	0x9c, 0x9a, 0x5a, 0xed, 0x08, 0x6e, 0x34, 0xa5, 0xf3, 0xd8, 0x25, 0xcc, 0x7b, 0xd9, 0x3e, 0x78,
	0xda, 0x64, 0x5c, 0x31, 0xee, 0xb4, 0xe8, 0x31, 0x09, 0xfa, 0xb8, 0x0c, 0x9b, 0x92, 0xf2, 0x3e,
	0x0d, 0xe6, 0x65, 0xe6, 0xab, 0xff, 0xa9, 0x73, 0x1b, 0xaa, 0xb9, 0x75, 0x5a, 0x54, 0xfa, 0x82,
	0x4b, 0x5a, 0xfb, 0x8c, 0x00, 0x2f, 0x54, 0xcf, 0x19, 0x1f, 0x15, 0x60, 0xbc, 0x86, 0xed, 0xd0,
	0xb7, 0xec, 0x28, 0xd1, 0xe9, 0x4d, 0x83, 0x2a, 0x6b, 0x3b, 0xeb, 0xbb, 0x97, 0x1b, 0x55, 0x2b,
	0xbb, 0xb3, 0x56, 0xd4, 0xc0, 0x7d, 0x7c, 0xf6, 0xc3, 0xd4, 0xbe, 0xfd, 0x34, 0x21, 0xda, 0x92,
	0xad, 0x2b, 0xb3, 0x6c, 0x87, 0x22, 0x04, 0x48, 0xc0, 0xdf, 0x04, 0x3d, 0x8d, 0x15, 0x51, 0x7f,
	0x45, 0x70, 0x7d, 0x71, 0x7c, 0x40, 0x5d, 0xea, 0x10, 0x25, 0x82, 0x55, 0x41, 0xaf, 0x82, 0x99,
	0xc3, 0x96, 0xd9, 0xf5, 0xf6, 0x31, 0xf1, 0x57, 0xb0, 0xeb, 0x31, 0x56, 0x44, 0xfd, 0x05, 0xc1,
	0xb5, 0xe8, 0x98, 0x0c, 0x19, 0x77, 0xe4, 0xaa, 0x80, 0x9b, 0x70, 0x2b, 0x93, 0x2c, 0xb3, 0xe3,
	0x4f, 0x48, 0xc0, 0x57, 0xb0, 0xe3, 0x31, 0xd6, 0x82, 0xba, 0xf1, 0x7b, 0x03, 0xd6, 0x9b, 0xd2,
	0xc1, 0x1f, 0x10, 0x94, 0x73, 0x2e, 0x8c, 0x7a, 0x1e, 0x50, 0xee, 0xec, 0xeb, 0x0f, 0x97, 0x0e,
	0x59, 0x00, 0xe1, 0xb7, 0xb0, 0x7d, 0xf1, 0xaa, 0xb8, 0x5b, 0x94, 0x2d, 0xd6, 0xea, 0x8d, 0x7f,
	0xd7, 0x46, 0x25, 0xdf, 0x23, 0x28, 0x65, 0x0e, 0xba, 0x5d, 0x94, 0xec, 0x42, 0x80, 0xfe, 0x60,
	0xc9, 0x80, 0x94, 0xeb, 0xc4, 0xa8, 0x16, 0xba, 0x8e, 0xb5, 0xc5, 0xae, 0xd3, 0xb3, 0x86, 0xdf,
	0x01, 0xce, 0x98, 0xb3, 0xbd, 0xc2, 0x4c, 0x49, 0xb9, 0x7e, 0x7f, 0x29, 0x79, 0xca, 0x6e, 0x62,
	0x4e, 0x0a, 0xed, 0xc6, 0xda, 0x62, 0xbb, 0xe9, 0x1f, 0x7d, 0xff, 0xd9, 0xd9, 0xd8, 0x40, 0xe7,
	0x63, 0x03, 0xfd, 0x1a, 0x1b, 0xe8, 0xd3, 0xc4, 0xd0, 0xce, 0x27, 0x86, 0xf6, 0x7d, 0x62, 0x68,
	0xaf, 0x6c, 0x87, 0xa9, 0x37, 0x83, 0xae, 0xd5, 0x13, 0x9e, 0xed, 0xd3, 0xa0, 0x27, 0x24, 0x93,
	0x7b, 0x2e, 0xe9, 0x4a, 0x3b, 0x7c, 0xeb, 0x47, 0x89, 0xd7, 0x5e, 0x9d, 0xf8, 0x54, 0x76, 0x37,
	0xc3, 0xb7, 0xfb, 0xde, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xda, 0xdb, 0x8e, 0x0c, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ClaimUSDFMintingReward is a message type used to claim USDF minting rewards
	ClaimUSDFMintingReward(ctx context.Context, in *MsgClaimUSDFMintingReward, opts ...grpc.CallOption) (*MsgClaimUSDFMintingRewardResponse, error)
	// ClaimJinxReward is a message type used to claim Jinx liquidity provider rewards
	ClaimJinxReward(ctx context.Context, in *MsgClaimJinxReward, opts ...grpc.CallOption) (*MsgClaimJinxRewardResponse, error)
	// ClaimDelegatorReward is a message type used to claim delegator rewards
	ClaimDelegatorReward(ctx context.Context, in *MsgClaimDelegatorReward, opts ...grpc.CallOption) (*MsgClaimDelegatorRewardResponse, error)
	// ClaimSwapReward is a message type used to claim swap rewards
	ClaimSwapReward(ctx context.Context, in *MsgClaimSwapReward, opts ...grpc.CallOption) (*MsgClaimSwapRewardResponse, error)
	// ClaimSavingsReward is a message type used to claim savings rewards
	ClaimSavingsReward(ctx context.Context, in *MsgClaimSavingsReward, opts ...grpc.CallOption) (*MsgClaimSavingsRewardResponse, error)
	// ClaimEarnReward is a message type used to claim earn rewards
	ClaimEarnReward(ctx context.Context, in *MsgClaimEarnReward, opts ...grpc.CallOption) (*MsgClaimEarnRewardResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClaimUSDFMintingReward(ctx context.Context, in *MsgClaimUSDFMintingReward, opts ...grpc.CallOption) (*MsgClaimUSDFMintingRewardResponse, error) {
	out := new(MsgClaimUSDFMintingRewardResponse)
	err := c.cc.Invoke(ctx, "/fury.incentive.v1beta1.Msg/ClaimUSDFMintingReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimJinxReward(ctx context.Context, in *MsgClaimJinxReward, opts ...grpc.CallOption) (*MsgClaimJinxRewardResponse, error) {
	out := new(MsgClaimJinxRewardResponse)
	err := c.cc.Invoke(ctx, "/fury.incentive.v1beta1.Msg/ClaimJinxReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimDelegatorReward(ctx context.Context, in *MsgClaimDelegatorReward, opts ...grpc.CallOption) (*MsgClaimDelegatorRewardResponse, error) {
	out := new(MsgClaimDelegatorRewardResponse)
	err := c.cc.Invoke(ctx, "/fury.incentive.v1beta1.Msg/ClaimDelegatorReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimSwapReward(ctx context.Context, in *MsgClaimSwapReward, opts ...grpc.CallOption) (*MsgClaimSwapRewardResponse, error) {
	out := new(MsgClaimSwapRewardResponse)
	err := c.cc.Invoke(ctx, "/fury.incentive.v1beta1.Msg/ClaimSwapReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimSavingsReward(ctx context.Context, in *MsgClaimSavingsReward, opts ...grpc.CallOption) (*MsgClaimSavingsRewardResponse, error) {
	out := new(MsgClaimSavingsRewardResponse)
	err := c.cc.Invoke(ctx, "/fury.incentive.v1beta1.Msg/ClaimSavingsReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimEarnReward(ctx context.Context, in *MsgClaimEarnReward, opts ...grpc.CallOption) (*MsgClaimEarnRewardResponse, error) {
	out := new(MsgClaimEarnRewardResponse)
	err := c.cc.Invoke(ctx, "/fury.incentive.v1beta1.Msg/ClaimEarnReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ClaimUSDFMintingReward is a message type used to claim USDF minting rewards
	ClaimUSDFMintingReward(context.Context, *MsgClaimUSDFMintingReward) (*MsgClaimUSDFMintingRewardResponse, error)
	// ClaimJinxReward is a message type used to claim Jinx liquidity provider rewards
	ClaimJinxReward(context.Context, *MsgClaimJinxReward) (*MsgClaimJinxRewardResponse, error)
	// ClaimDelegatorReward is a message type used to claim delegator rewards
	ClaimDelegatorReward(context.Context, *MsgClaimDelegatorReward) (*MsgClaimDelegatorRewardResponse, error)
	// ClaimSwapReward is a message type used to claim swap rewards
	ClaimSwapReward(context.Context, *MsgClaimSwapReward) (*MsgClaimSwapRewardResponse, error)
	// ClaimSavingsReward is a message type used to claim savings rewards
	ClaimSavingsReward(context.Context, *MsgClaimSavingsReward) (*MsgClaimSavingsRewardResponse, error)
	// ClaimEarnReward is a message type used to claim earn rewards
	ClaimEarnReward(context.Context, *MsgClaimEarnReward) (*MsgClaimEarnRewardResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClaimUSDFMintingReward(ctx context.Context, req *MsgClaimUSDFMintingReward) (*MsgClaimUSDFMintingRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimUSDFMintingReward not implemented")
}
func (*UnimplementedMsgServer) ClaimJinxReward(ctx context.Context, req *MsgClaimJinxReward) (*MsgClaimJinxRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimJinxReward not implemented")
}
func (*UnimplementedMsgServer) ClaimDelegatorReward(ctx context.Context, req *MsgClaimDelegatorReward) (*MsgClaimDelegatorRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimDelegatorReward not implemented")
}
func (*UnimplementedMsgServer) ClaimSwapReward(ctx context.Context, req *MsgClaimSwapReward) (*MsgClaimSwapRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimSwapReward not implemented")
}
func (*UnimplementedMsgServer) ClaimSavingsReward(ctx context.Context, req *MsgClaimSavingsReward) (*MsgClaimSavingsRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimSavingsReward not implemented")
}
func (*UnimplementedMsgServer) ClaimEarnReward(ctx context.Context, req *MsgClaimEarnReward) (*MsgClaimEarnRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimEarnReward not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClaimUSDFMintingReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimUSDFMintingReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimUSDFMintingReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fury.incentive.v1beta1.Msg/ClaimUSDFMintingReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimUSDFMintingReward(ctx, req.(*MsgClaimUSDFMintingReward))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimJinxReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimJinxReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimJinxReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fury.incentive.v1beta1.Msg/ClaimJinxReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimJinxReward(ctx, req.(*MsgClaimJinxReward))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimDelegatorReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimDelegatorReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimDelegatorReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fury.incentive.v1beta1.Msg/ClaimDelegatorReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimDelegatorReward(ctx, req.(*MsgClaimDelegatorReward))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimSwapReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimSwapReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimSwapReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fury.incentive.v1beta1.Msg/ClaimSwapReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimSwapReward(ctx, req.(*MsgClaimSwapReward))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimSavingsReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimSavingsReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimSavingsReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fury.incentive.v1beta1.Msg/ClaimSavingsReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimSavingsReward(ctx, req.(*MsgClaimSavingsReward))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimEarnReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimEarnReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimEarnReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fury.incentive.v1beta1.Msg/ClaimEarnReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimEarnReward(ctx, req.(*MsgClaimEarnReward))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fury.incentive.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimUSDFMintingReward",
			Handler:    _Msg_ClaimUSDFMintingReward_Handler,
		},
		{
			MethodName: "ClaimJinxReward",
			Handler:    _Msg_ClaimJinxReward_Handler,
		},
		{
			MethodName: "ClaimDelegatorReward",
			Handler:    _Msg_ClaimDelegatorReward_Handler,
		},
		{
			MethodName: "ClaimSwapReward",
			Handler:    _Msg_ClaimSwapReward_Handler,
		},
		{
			MethodName: "ClaimSavingsReward",
			Handler:    _Msg_ClaimSavingsReward_Handler,
		},
		{
			MethodName: "ClaimEarnReward",
			Handler:    _Msg_ClaimEarnReward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fury/incentive/v1beta1/tx.proto",
}

func (m *Selection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Selection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Selection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MultiplierName) > 0 {
		i -= len(m.MultiplierName)
		copy(dAtA[i:], m.MultiplierName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MultiplierName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimUSDFMintingReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimUSDFMintingReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimUSDFMintingReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MultiplierName) > 0 {
		i -= len(m.MultiplierName)
		copy(dAtA[i:], m.MultiplierName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MultiplierName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimUSDFMintingRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimUSDFMintingRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimUSDFMintingRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClaimJinxReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimJinxReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimJinxReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomsToClaim) > 0 {
		for iNdEx := len(m.DenomsToClaim) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DenomsToClaim[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimJinxRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimJinxRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimJinxRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClaimDelegatorReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimDelegatorReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimDelegatorReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomsToClaim) > 0 {
		for iNdEx := len(m.DenomsToClaim) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DenomsToClaim[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimDelegatorRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimDelegatorRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimDelegatorRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClaimSwapReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimSwapReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimSwapReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomsToClaim) > 0 {
		for iNdEx := len(m.DenomsToClaim) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DenomsToClaim[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimSwapRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimSwapRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimSwapRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClaimSavingsReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimSavingsReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimSavingsReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomsToClaim) > 0 {
		for iNdEx := len(m.DenomsToClaim) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DenomsToClaim[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimSavingsRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimSavingsRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimSavingsRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClaimEarnReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimEarnReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimEarnReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomsToClaim) > 0 {
		for iNdEx := len(m.DenomsToClaim) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DenomsToClaim[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimEarnRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimEarnRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimEarnRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Selection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MultiplierName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimUSDFMintingReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MultiplierName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimUSDFMintingRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClaimJinxReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.DenomsToClaim) > 0 {
		for _, e := range m.DenomsToClaim {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgClaimJinxRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClaimDelegatorReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.DenomsToClaim) > 0 {
		for _, e := range m.DenomsToClaim {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgClaimDelegatorRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClaimSwapReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.DenomsToClaim) > 0 {
		for _, e := range m.DenomsToClaim {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgClaimSwapRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClaimSavingsReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.DenomsToClaim) > 0 {
		for _, e := range m.DenomsToClaim {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgClaimSavingsRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClaimEarnReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.DenomsToClaim) > 0 {
		for _, e := range m.DenomsToClaim {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgClaimEarnRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Selection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Selection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Selection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultiplierName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultiplierName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimUSDFMintingReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimUSDFMintingReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimUSDFMintingReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultiplierName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultiplierName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimUSDFMintingRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimUSDFMintingRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimUSDFMintingRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimJinxReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimJinxReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimJinxReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomsToClaim", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomsToClaim = append(m.DenomsToClaim, Selection{})
			if err := m.DenomsToClaim[len(m.DenomsToClaim)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimJinxRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimJinxRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimJinxRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimDelegatorReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimDelegatorReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimDelegatorReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomsToClaim", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomsToClaim = append(m.DenomsToClaim, Selection{})
			if err := m.DenomsToClaim[len(m.DenomsToClaim)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimDelegatorRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimDelegatorRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimDelegatorRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimSwapReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimSwapReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimSwapReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomsToClaim", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomsToClaim = append(m.DenomsToClaim, Selection{})
			if err := m.DenomsToClaim[len(m.DenomsToClaim)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimSwapRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimSwapRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimSwapRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimSavingsReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimSavingsReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimSavingsReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomsToClaim", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomsToClaim = append(m.DenomsToClaim, Selection{})
			if err := m.DenomsToClaim[len(m.DenomsToClaim)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimSavingsRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimSavingsRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimSavingsRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimEarnReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimEarnReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimEarnReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomsToClaim", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomsToClaim = append(m.DenomsToClaim, Selection{})
			if err := m.DenomsToClaim[len(m.DenomsToClaim)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimEarnRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimEarnRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimEarnRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
